CupCarbon v. U-One 3.8.2
----------------
name:Cenario3
zoom:2
centerposition_la:41.54864830438062
centerposition_lo:-8.402384519577026
map:0
display_details:false
draw_radio_links:true
draw_sensor_arrows:true
radio_links_color:3
draw_marker_arrows:false
display_rl_distance:false
propagation:false
display_marker_distance:true
display_radio_messages:false
draw_script_file_name:true
display_print_messages:true
